### ISSUE TITLE
Page Redirection « localhost » error

### ISSUE THREAD

**Issue by Baptlaser** [MrAugu/simple-discordjs-dashboard#11]
Hello i configurate all de file and it is working bit when here i clik in « Autoriser » he moove me in a page error
![C4C84390-E27E-4766-AA26-5A4A72E28E3F](https://user-images.githubusercontent.com/62359510/96372939-b8869c80-1169-11eb-9724-28d05e351dbd.jpeg)
moove here 
![9F9EBC5B-8A09-43E1-80D5-E2AC7A12893B](https://user-images.githubusercontent.com/62359510/96372950-c50af500-1169-11eb-8bd4-00ea3e675dfe.jpeg)
My code ⬇️
![B333091D-DC92-4DBD-807C-B0A7BF35B969](https://user-images.githubusercontent.com/62359510/96372987-eff54900-1169-11eb-9480-667603157450.jpeg)
![EC2E7DF5-DAB4-4720-A6EA-2B6A26250F99](https://user-images.githubusercontent.com/62359510/96372989-f1267600-1169-11eb-93f6-2f16f8e2f29e.jpeg)

**Comment by MrAugu** [comment]
I do not know many of things which could influence this, you are doing something wrong most probably. Re-open once you can supply full information.
