### ISSUE TITLE
user.avatarURL

### ISSUE THREAD

**Issue by xMuffionex** [MrAugu/simple-discordjs-dashboard#13]
Hi, how to get user.avatarURL in header.ejs?

**Comment by MrAugu** [comment]
You need to format the CDN url.

`https://cdn.discordapp.com/:user_id/:hash.png?size=256`

`:user_id` - Is `user.id` property.
`:hash` - Is `user.avatar` property.

The `user.avatar` will be `null` if user does not have anu avatar, so you need to handle that condition as well.
