### ISSUE TITLE
switcher

### ISSUE THREAD

**Issue by xMuffionex** [MrAugu/simple-discordjs-dashboard#14]
Hi, i'm using quick.db in my bot, and changing prefix works very good! (thx a lot). bUt i have leveling system too and i want to add something like this: https://i.imgur.com/QNJQB1K.gif and if is disabled returns false (like prefix, when you are changing it, it returns a post). but idk how to create backend for this switch. Can someone help?

**Comment by adnap333** [comment]
Try using bootstrap 4 inside the ejs file and set button type to submit. I hope this works cuz I am trying to do the same and I have not yet tested it.

**Comment by xMuffionex** [comment]
> Try using bootstrap 4 inside the ejs file and set button type to submit. I hope this works cuz I am trying to do the same and I have not yet tested it.
> Use jquery .click and ajax to post it to dashboard.js

will try! thx
