### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Jeydin21** [MrAugu/simple-discordjs-dashboard#15]
Hey, could we have a demo of the dashboard? If that's not available, some screenshots wouldn't go amiss as well.

**Comment by ToledoSDL** [comment]
Why do you not try run?

**Comment by Jeydin21** [comment]
I tried running it the other day but I was just curious as to what it
looked like, as I don't really have time to work on that right now.

**Comment by Jeydin21** [comment]
I tried running it the other day but I was just curious as to what it looked like, as I don't really have time to work on that right now. So could you please send some pictures as to what it looks like before I start working on it? That would really help me a bunch.

**Comment by Myst82015** [comment]
Since this dashboard is only to show the basic functionality of OAuth there isn't much to see.

**Comment by Jeydin21** [comment]
Fine, so be it.
