### ISSUE TITLE
dashboard.js guild.members.cache.get not working

### ISSUE THREAD

**Issue by m0ri-wk** [MrAugu/simple-discordjs-dashboard#16]
With the recent changes to discord.js, this will need to be changed from:

`const member = guild.members.cache.get(req.user.id);`
to
`const member = await guild.members.fetch(req.user.id);`

**Comment by MrAugu** [comment]
May you create a pull request with the required updates?

**Comment by m0ri-wk** [comment]
I've done that but not sure how to link that pull request to this issue

**Comment by Myst82015** [comment]
To solve this issue as quickly as possible I made the pull request https://github.com/MrAugu/simple-discordjs-dashboard/pull/17 .

**Comment by Myst82015** [comment]
@m0ri-wk 
I did test it with const member = guild.members.cache.get(req.user.id);
and it works perfetly fine.
Therefore i closed https://github.com/MrAugu/simple-discordjs-dashboard/pull/17 .

**Comment by typicalninja493** [comment]
mmm not for me tho

**Comment by m0ri-wk** [comment]
Ok, I was seeing the issue in a large member server. Check this https://discord.com/channels/222078108977594368/222078108977594368/771434053244944494 for where I found out about it. If the Discord.js Official server.

**Comment by MrAugu** [comment]
If this issue persists, please bring conclusive information which we can make decisions of and fix any issues. As there is nothing I can do from this little information considering it works for other people I will close this issue.
