### ISSUE TITLE
Poll: Create multiple versions of dashboard.

### ISSUE THREAD

**Issue by MrAugu** [MrAugu/simple-discordjs-dashboard#18]
Basically, create multiple versions as multiple branches, for instance existing one could become `backend-focused` and create other ones such as `front-bootsrap-focused (ejs)`, `framework-focused (vue). You can tell your opinion in the comments.

*React to chose.*
👍 - Yes!
👎 - No!

**Comment by xMuffionex** [comment]
i think, it's good, i can conturibute to something like that ;)
