### ISSUE TITLE
No redirection

### ISSUE THREAD

**Issue by alex0754** [MrAugu/simple-discordjs-dashboard#20]
Hey,
when I click on "change settings", nothing happens. I haven't changed anything in the code. 
![image](https://user-images.githubusercontent.com/40841270/101999263-4cc43a00-3ca9-11eb-99a8-c2dbd84b66e6.png)

**Comment by SiderealArt** [comment]
Hello, I've got the same issue.
Can you tell me how you solved it?
Thanks.

**Comment by alex0754** [comment]
Hello, change the port in the config file !
