### ISSUE TITLE
Suggestion: Support other Databases/Storage Adapters

### ISSUE THREAD

**Issue by TheCuteFoxxy** [MrAugu/simple-discordjs-dashboard#24]
**Details:**
Support other Databases such as SQLite and/or Storage Adapters such as [Keyv](https://github.com/lukechilds/keyv)

**Benefits:**
Supporting other databases would allow a larger range of support for different environments, especially production environments that may not utilize Mongo.

**Comment by MrAugu** [comment]
Will try to add more branches.
