### ISSUE TITLE
Adding The Endpoint Isn't Working

### ISSUE THREAD

**Issue by phyouthcenter1** [MrAugu/simple-discordjs-dashboard#25]
<img width="2459" alt="Screen Shot 2021-02-01 at 11 27 50 AM" src="https://user-images.githubusercontent.com/67077196/106510277-90564b80-6483-11eb-8e6a-b10ede00161e.png">

**Comment by Myst82015** [comment]
> 
> 
> <img alt="Screen Shot 2021-02-01 at 11 27 50 AM" width="2000" src="https://user-images.githubusercontent.com/67077196/106510277-90564b80-6483-11eb-8e6a-b10ede00161e.png">

The redirt url does not belong there. On the left side you see OAuth, click there and add the callback.
