### ISSUE TITLE
TokenError

### ISSUE THREAD

**Issue by jaydenkoh** [MrAugu/simple-discordjs-dashboard#27]
![image](https://user-images.githubusercontent.com/66878523/107301361-4f2eee80-6ab6-11eb-9810-65c958562f48.png)

**Comment by Myst82015** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/66878523/107301361-4f2eee80-6ab6-11eb-9810-65c958562f48.png)

This error is thrown by the strategy package. You probably clicked Login to often. Restart the application and clicking Login only once should to the trick
