### ISSUE TITLE
New users problem

### ISSUE THREAD

**Issue by JewHyper** [MrAugu/simple-discordjs-dashboard#28]
Every time I restart the bot / someone is leaving and rejoining the server the bot is creating a new user for this account.
Is there any way I can prevent the bot from creating new and new users for the same account if there is already an existing user?

**Comment by MrAugu** [comment]
You should be more detailed. (Closing this in 1 week if no further information is provided.)

**Comment by sathvik2377** [comment]
*hi its saying like this how to fix and some time discord.com refused to connect also how to fix*```Hmmm… can't reach this pagelocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED ```

**Comment by Myst82015** [comment]
> 
> 
> _hi its saying like this how to fix and some time discord.com refused to connect also how to fix_```Hmmm… can't reach this pagelocalhost refused to connect.
> Try:
> 
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_REFUSED ```

I don't understand what your problem could be at all....
We need way more details to help you.

**Comment by koder-king** [comment]
> _hi its saying like this how to fix and some time discord.com refused to connect also how to fix_```Hmmm… can't reach this pagelocalhost refused to connect.
> Try:
> 
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_REFUSED ```

probably cuz you tried connecting using mobile. Use a system/PC instead

**Comment by Myst82015** [comment]
> 
> 
> > _hi its saying like this how to fix and some time discord.com refused to connect also how to fix_```Hmmm… can't reach this pagelocalhost refused to connect.
> > Try:
> > Checking the connection
> > Checking the proxy and the firewall
> > ERR_CONNECTION_REFUSED ```
> 
> probably cuz you tried connecting using mobile. Use a system/PC instead

That coult be it but as MrAugu and myself said before, he / she didn't provide enough informations.
If you still need help, check out our Discord server instead of making an issue on github. (https://discord.gg/rk7cVyk)
