### ISSUE TITLE
Settings page doesn't gets loaded

### ISSUE THREAD

**Issue by Ayush4385** [MrAugu/simple-discordjs-dashboard#44]
When I click edit settings the pagedoesnt loads

**Comment by Ayush4385** [comment]
I found the error was with my mongodb

**Comment by Thibaut12345** [comment]
Hey Ayush4385! unfortunately I have the same problem... May I know how you solved this?

**Comment by Ayush4385** [comment]
@Thibaut12345 Make another cluster which can connect from any IP and use that

**Comment by Thibaut12345** [comment]
> @Thibaut12345 Make another cluster which can connect from any IP and use that

I can't do this because I already have a free cluster. If I want to create another I have to pay according to mongoDB.

**Comment by Ayush4385** [comment]
@Thibaut12345 create another folder then make

**Comment by Thibaut12345** [comment]
@Ayush4385 I have created new project with a new cluster. Allow connections from all IPs. still not working :( Do you have discord?

**Comment by Ayush4385** [comment]
Yes

**Comment by Thibaut12345** [comment]
could you maybe add 2Snow#1915? it still doesn't work and talking here is a bit difficult

**Comment by Ayush4385** [comment]
@Thibaut12345 i have sent you friend request(Ayush#4385)
