### ISSUE TITLE
OAuth URL outdated or incorrectly formatted!

### ISSUE THREAD

**Issue by AtaraxiaCodes** [MrAugu/simple-discordjs-dashboard#6]
At dashboard/template/dashboard.ejs, the OAuth URL that was formatted (quite ingeniously might I add) no longer works. I am researching if this is because there was a format update of if it is because Discord has new OAuth policies, but whatever the case is, the URL doesn’t work.

MrAugu if you could please fix this, I (and many others) would be delighted for sure! Thanks for reading and more thanks if you can fix it! - Ataraxia

**Comment by MrAugu** [comment]
I will look forward doing so.

**Comment by Loser357** [comment]
I can fix it!

**Comment by Mythyo1** [comment]
Its outdated. I will give you a new package. And a pull request.

**Comment by MrAugu** [comment]
Will be fixed in a new version.
