### ISSUE TITLE
Suggestion List

### ISSUE THREAD

**Issue by MrAugu** [MrAugu/simple-discordjs-dashboard#9]
If you have things that you would like me to add, say it in this issue and I will look forward implementing them. You can suggest about anything. 

*Next updates are scheduled within 1 week.*

**Comment by Pr0H4cker** [comment]
How do I make the redirect url. I cannot start the bot dashboard

**Comment by tovade** [comment]
nicer looking fonts

**Comment by tovade** [comment]
a guide on how to make it in the middle etc

**Comment by Myst82015** [comment]
> 
> 
> nicer looking fonts

Since this dashboard is simply for showing the way how to use discord oauth methods I am pretty sure MrAugu won't implement any css.

**Comment by Myst82015** [comment]
> a guide on how to make it in the middle etc
> in settings.ejs

What exactly do you mean with that?

**Comment by tovade** [comment]
> 
> 
> > a guide on how to make it in the middle etc
> 
> > in settings.ejs
> 
> 
> 
> What exactly do you mean with that?

Like now we only display the settings on right or left but not in the middle

**Comment by MrAugu** [comment]
> > > a guide on how to make it in the middle etc
> > 
> > 
> > > in settings.ejs
> > 
> > 
> > What exactly do you mean with that?
> 
> Like now we only display the settings on right or left but not in the middle

Do you mean styling?

**Comment by tovade** [comment]
he said u wont do it i just wanna know how u make a setting in the middle like we have prefix on the left but idk how to make it display in the middle of our screen

**Comment by Myst82015** [comment]
That's simple css stuff, how about you google that?

**Comment by UselessPyDev** [comment]
I am having the same problem as Pr0H4cker.
"How do I make the redirect url. I cannot start the bot dashboard". I am not quite sure how to do this. If someone could help, that would be much appreciated!

**Comment by Myst82015** [comment]
> 
> 
> I am having the same problem as Pr0H4cker.
> "How do I make the redirect url. I cannot start the bot dashboard". I am not quite sure how to do this. If someone could help, that would be much appreciated!

MrAugu is aware of that and will fix it soon.

**Comment by Oli-idk** [comment]
cookie so you dont have to login every time you reload the page

**Comment by MrAugu** [comment]
I will take in consideration all of these,
